require_relative '../../node_modules/.pnpm/@capacitor+ios@7.6.5_@capacitor+core@7.6.2/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.1'
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@7.6.5_@capacitor+core@7.6.2/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@7.6.5_@capacitor+core@7.6.2/node_modules/@capacitor/ios'
  pod 'CantooCapacitorOnnx', :path => '../../../..'
  pod 'CapacitorFileTransfer', :path => '../../node_modules/.pnpm/@capacitor+file-transfer@1.0.12_@capacitor+core@7.6.2/node_modules/@capacitor/file-transfer'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@7.1.8_@capacitor+core@7.6.2/node_modules/@capacitor/filesystem'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
